<ul>
    <li><a href="https://solutionpartners.adobe.com/fragments/partners/a1X1O00000B6IUCUA3.html" target="_blank"><img src='<?php echo $this->getViewFileUrl('images/logo-adobe.webp'); ?>' alt="" width="150"></a></li>
    <li><a href="https://www.harriswebworks.com/magento-certified-partner-agency/" target="_blank"><img src='<?php echo $this->getViewFileUrl('images/logo-magento.webp'); ?>' alt="" width="150"></a></li>
    <li>
        <div id="mni-membership-637376679160663645">
            <div class=" mn-widget-member">
                <div class=" mn-widget-member-name">Harris Web Works</div>
                <div class=" mn-widget-member-text">Proud Member of</div>
                <div class=" mn-widget-member-assoc"><a href="https://www.manufacturect.org" target="_blank" class=" mn-widget-member-link"><img src='<?php echo $this->getViewFileUrl('images/ManCT__Square__TD__Tag__C.webp'); ?>' alt="ManufactureCT" title="ManufactureCT" class=" mn-widget-member-logo"></a></div>
            </div>
        </div>

    </li>
</ul>