<?php
/**
 * Top menu for store
 *
 * @var $block \Harriswebworks\Menumanager\Block\Menu
 */
?>
<?php $columnsLimit = $block->getColumnsLimit() ? $block->getColumnsLimit() : 0; ?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) ?>
<?php if ($_menu) { ?>
    <nav class=" main-menu navigation" role="navigation">
        <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
            <?php /* @escapeNotVerified */ echo $_menu; ?>
        </ul>
    </nav>
<?php } ?>